// nuxt/app/app.vue
<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from "vue";

import { createAppConfig } from "./lib/config";
import { detectEnvironment, type RuntimeEnvironment } from "./lib/environment";
import { createEvmWallet, type EvmConnection } from "./lib/wispEvm";
import { createNativeWallet, type NativeConnection } from "./lib/wispNative";
import { createWalletConnect } from "./lib/walletConnect";

useHead({
  title: "Wisp dApp Example · Nuxt",
  meta: [
    {
      name: "description",
      content: "Nuxt example for Wisp Wallet, WindStack, VEX Native, and VEX EVM.",
    },
  ],
});

const runtimeConfig = useRuntimeConfig();
const config = createAppConfig(runtimeConfig.public as Record<string, unknown>);
const nativeWallet = createNativeWallet(config);
const evmWallet = createEvmWallet(config);
const walletConnect = createWalletConnect(config);

const environment = ref<RuntimeEnvironment>({
  runtime: "Desktop browser",
  isAndroid: false,
  isTelegram: false,
  hasInjectedNative: false,
  hasInjectedEvm: false,
  isSecureContext: false,
});
const native = ref<NativeConnection | null>(null);
const restoringNative = ref(true);
const nativeBalance = ref("");
const nativeForm = reactive({ recipient: "", amount: "0.0001", memo: "Wisp example" });
const evm = ref<EvmConnection | null>(null);
const evmBalance = ref("");
const evmForm = reactive({ recipient: "", amount: "0.000001" });
const busy = ref("");
const error = ref("");
const result = ref<{ title: string; value: unknown; at: string } | null>(null);

let stopNative: () => void = () => {};
let stopEvm: () => void = () => {};

onMounted(() => {
  environment.value = detectEnvironment();
  stopNative = nativeWallet.subscribe((connection) => {
    native.value = connection;
  });
  stopEvm = evmWallet.subscribe((connection) => {
    evm.value = connection;
  });

  void nativeWallet
    .restore()
    .catch((caught) => {
      error.value = message(caught);
    })
    .finally(() => {
      restoringNative.value = false;
    });
});

onUnmounted(() => {
  stopNative();
  stopEvm();
});

function message(caught: unknown) {
  return caught instanceof Error ? caught.message : "Unexpected request failure.";
}

async function run<T>(title: string, operation: () => Promise<T>) {
  if (busy.value) return undefined;
  busy.value = title;
  error.value = "";
  try {
    const value = await operation();
    result.value = { title, value, at: new Date().toISOString() };
    return value;
  } catch (caught) {
    error.value = message(caught);
    return undefined;
  } finally {
    busy.value = "";
  }
}

async function handleConnectNative() {
  await run("Native connected", async () => {
    const connection = await nativeWallet.connect();
    native.value = connection;
    return connection;
  });
}

async function handleNativeAccount() {
  await run("Native account", nativeWallet.getAccount);
}

async function handleNativeBalance() {
  await run("Native balance", async () => {
    const balance = await nativeWallet.getBalance();
    nativeBalance.value = balance;
    return balance;
  });
}

async function handleNativeTransfer() {
  if (!window.confirm("Request this real VEX Native mainnet transfer in Wisp Wallet?")) return;
  await run("Native transaction", () => nativeWallet.sendTransfer({ ...nativeForm }));
}

async function handleConnectInjectedEvm() {
  await run("Wisp EVM connected", async () => {
    const connection = await evmWallet.connect();
    evm.value = connection;
    return connection;
  });
}

async function handleConnectWalletConnect() {
  await run("WalletConnect connected", async () => {
    const provider = await walletConnect.connect();
    const connection = await evmWallet.connect(provider, "WalletConnect v2");
    evm.value = connection;
    return connection;
  });
}

async function handleEnsureNetwork() {
  await run("VEX EVM network ready", async () => {
    const chainId = await evmWallet.ensureNetwork();
    if (evm.value) evm.value = { ...evm.value, chainId };
    return chainId;
  });
}

async function handleEvmAddress() {
  await run("EVM address", evmWallet.getAddress);
}

async function handleEvmBalance() {
  await run("EVM balance", async () => {
    const balance = await evmWallet.getBalance();
    evmBalance.value = balance;
    return balance;
  });
}

async function handleEvmTransfer() {
  if (!window.confirm("Request this real VEX EVM mainnet transfer in Wisp Wallet?")) return;
  await run("EVM transaction", async () => ({
    transactionHash: await evmWallet.sendTransaction({ ...evmForm }),
  }));
}

async function handleNativeDisconnect() {
  await run("Native disconnected", async () => {
    await nativeWallet.disconnect();
    native.value = null;
    nativeBalance.value = "";
    return "Disconnected";
  });
}

async function handleEvmDisconnect() {
  await run("EVM disconnected", async () => {
    if (evm.value?.method === "WalletConnect v2") await walletConnect.disconnect();
    evmWallet.disconnect();
    evm.value = null;
    evmBalance.value = "";
    return "Disconnected";
  });
}

function renderedResult() {
  return result.value
    ? JSON.stringify(result.value.value, null, 2)
    : "Connect a wallet or send a transaction to see the result.";
}
</script>

<template>
  <main class="page-shell">
    <header class="hero">
      <span class="eyebrow">Nuxt 4 + Vue 3 + TypeScript</span>
      <h1>Wisp dApp Example</h1>
      <p>Connect Wisp Wallet, restore an existing session, read balances, and send example VEX Native or VEX EVM transactions.</p>
    </header>

    <div v-if="error" class="notice error" role="alert"><strong>Request failed</strong><span>{{ error }}</span></div>
    <div v-if="busy" class="notice pending" role="status">Waiting: {{ busy }}</div>

    <section class="card full">
      <div class="section-heading"><div><span class="step">01</span><h2>Environment</h2></div><span class="status">{{ environment.runtime }}</span></div>
      <dl class="info-grid">
        <div class="info-row"><dt>Runtime</dt><dd>{{ environment.runtime }}</dd></div>
        <div class="info-row"><dt>Secure context</dt><dd>{{ environment.isSecureContext ? "Yes" : "No — Wisp Telegram requires HTTPS" }}</dd></div>
        <div class="info-row"><dt>Wisp Native</dt><dd>{{ environment.hasInjectedNative ? "Available" : "Not detected" }}</dd></div>
        <div class="info-row"><dt>Wisp EVM</dt><dd>{{ environment.hasInjectedEvm ? "Available" : "Not detected" }}</dd></div>
        <div class="info-row"><dt>Native RPC</dt><dd>{{ config.nativeRpc }}</dd></div>
        <div class="info-row"><dt>EVM RPC</dt><dd>{{ config.evmRpc }}</dd></div>
        <div class="info-row"><dt>Wisp API</dt><dd>{{ config.wispApiUrl }}</dd></div>
      </dl>
    </section>

    <div class="columns">
      <section class="card">
        <div class="section-heading"><div><span class="step">02</span><h2>VEX Native</h2></div><span class="status">{{ restoringNative ? "Restoring…" : native?.method || "Disconnected" }}</span></div>
        <div class="button-grid">
          <button :disabled="Boolean(busy) || restoringNative" @click="handleConnectNative">Connect Wisp Native</button>
          <button class="secondary" :disabled="Boolean(busy) || restoringNative || !native" @click="handleNativeAccount">Get Account</button>
          <button class="secondary" :disabled="Boolean(busy) || restoringNative || !native" @click="handleNativeBalance">Get VEX Balance</button>
          <button class="ghost" :disabled="Boolean(busy) || restoringNative || !native" @click="handleNativeDisconnect">Disconnect</button>
        </div>
        <p class="hint">A saved Wisp session is checked after hydration. A new connection request only starts when you press Connect.</p>
        <dl class="compact-info">
          <div class="info-row"><dt>Account</dt><dd>{{ native?.account.permissionLevel || "—" }}</dd></div>
          <div class="info-row"><dt>Chain</dt><dd>{{ native?.chainId || config.nativeChainId }}</dd></div>
          <div class="info-row"><dt>Balance</dt><dd>{{ nativeBalance || "—" }}</dd></div>
        </dl>
        <form class="transaction-form" @submit.prevent="handleNativeTransfer">
          <h3>Native transfer</h3>
          <label>Recipient<input v-model="nativeForm.recipient" required placeholder="receiver" autocomplete="off" /></label>
          <label>Amount (VEX)<input v-model="nativeForm.amount" required inputmode="decimal" /></label>
          <label>Memo<input v-model="nativeForm.memo" maxlength="256" /></label>
          <button type="submit" :disabled="Boolean(busy) || restoringNative || !native">Send Native Transaction</button>
        </form>
      </section>

      <section class="card">
        <div class="section-heading"><div><span class="step">03</span><h2>VEX EVM</h2></div><span class="status">{{ evm?.method || "Disconnected" }}</span></div>
        <div class="button-grid">
          <button :disabled="Boolean(busy)" @click="handleConnectInjectedEvm">Connect Wisp EVM</button>
          <button class="secondary" :disabled="Boolean(busy) || !walletConnect.isConfigured()" @click="handleConnectWalletConnect">Connect WalletConnect v2</button>
          <button class="secondary" :disabled="Boolean(busy) || !evm" @click="handleEnsureNetwork">Switch/Add VEX EVM Network</button>
          <button class="secondary" :disabled="Boolean(busy) || !evm" @click="handleEvmAddress">Get Address</button>
          <button class="secondary" :disabled="Boolean(busy) || !evm" @click="handleEvmBalance">Get Native VEX Balance</button>
          <button class="ghost" :disabled="Boolean(busy) || !evm" @click="handleEvmDisconnect">Disconnect</button>
        </div>
        <p v-if="!walletConnect.isConfigured()" class="hint">WalletConnect requires <code>NUXT_PUBLIC_WALLETCONNECT_PROJECT_ID</code>.</p>
        <dl class="compact-info">
          <div class="info-row"><dt>Address</dt><dd>{{ evm?.address || "—" }}</dd></div>
          <div class="info-row"><dt>Chain</dt><dd>{{ evm?.chainId || config.evmChainIdHex }}</dd></div>
          <div class="info-row"><dt>Balance</dt><dd>{{ evmBalance || "—" }}</dd></div>
        </dl>
        <form class="transaction-form" @submit.prevent="handleEvmTransfer">
          <h3>EVM transfer</h3>
          <label>Recipient<input v-model="evmForm.recipient" required placeholder="0x..." autocomplete="off" /></label>
          <label>Amount (VEX)<input v-model="evmForm.amount" required inputmode="decimal" /></label>
          <button type="submit" :disabled="Boolean(busy) || !evm">Send EVM Transaction</button>
        </form>
      </section>
    </div>

    <section class="card full">
      <div class="section-heading"><div><span class="step">04</span><h2>Wallet Information</h2></div></div>
      <dl class="info-grid">
        <div class="info-row"><dt>Native connection</dt><dd>{{ native?.method || "Not connected" }}</dd></div>
        <div class="info-row"><dt>Native account</dt><dd>{{ native?.account.permissionLevel || "—" }}</dd></div>
        <div class="info-row"><dt>EVM connection</dt><dd>{{ evm?.method || "Not connected" }}</dd></div>
        <div class="info-row"><dt>EVM address</dt><dd>{{ evm?.address || "—" }}</dd></div>
      </dl>
    </section>

    <section class="card full result-card">
      <div class="section-heading"><div><span class="step">05</span><h2>Latest Result</h2></div><span class="status">{{ result ? `${result.title} · ${result.at}` : "No request yet" }}</span></div>
      <pre>{{ renderedResult() }}</pre>
    </section>
  </main>
</template>

// react-vite/src/App.tsx
import { useEffect, useMemo, useState, type FormEvent } from "react";

import {
  VEX_EVM_CHAIN_ID_HEX,
  VEX_EVM_RPC,
  VEX_NATIVE_CHAIN_ID,
  VEX_NATIVE_RPC,
  WISP_API_URL,
} from "./config";
import { detectEnvironment } from "./lib/environment";
import {
  connectEvm,
  disconnectEvm,
  ensureVexEvmNetwork,
  getEvmAddress,
  getEvmBalance,
  sendEvmTransaction,
  subscribeEvm,
  type EvmConnection,
} from "./lib/wispEvm";
import {
  connectNative,
  disconnectNative,
  getNativeAccount,
  getNativeBalance,
  restoreNative,
  sendNativeTransfer,
  subscribeNative,
  type NativeConnection,
} from "./lib/wispNative";
import {
  connectWalletConnect,
  disconnectWalletConnect,
  isWalletConnectConfigured,
} from "./lib/walletConnect";

type ResultState = {
  title: string;
  value: unknown;
  at: string;
};

function message(error: unknown) {
  return error instanceof Error ? error.message : "Unexpected request failure.";
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div className="info-row">
      <dt>{label}</dt>
      <dd>{value || "—"}</dd>
    </div>
  );
}

export default function App() {
  const environment = useMemo(detectEnvironment, []);
  const [native, setNative] = useState<NativeConnection | null>(null);
  const [restoringNative, setRestoringNative] = useState(true);
  const [nativeBalance, setNativeBalance] = useState("");
  const [nativeForm, setNativeForm] = useState({
    recipient: "",
    amount: "0.0001",
    memo: "Wisp example",
  });
  const [evm, setEvm] = useState<EvmConnection | null>(null);
  const [evmBalance, setEvmBalance] = useState("");
  const [evmForm, setEvmForm] = useState({ recipient: "", amount: "0.000001" });
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [result, setResult] = useState<ResultState | null>(null);

  useEffect(() => {
    let mounted = true;
    const stopNative = subscribeNative((connection) => {
      if (mounted) setNative(connection);
    });
    const stopEvm = subscribeEvm((connection) => {
      if (mounted) setEvm(connection);
    });

    void restoreNative()
      .catch((caught) => {
        if (mounted) setError(message(caught));
      })
      .finally(() => {
        if (mounted) setRestoringNative(false);
      });

    return () => {
      mounted = false;
      stopNative();
      stopEvm();
    };
  }, []);

  async function run<T>(title: string, operation: () => Promise<T>) {
    if (busy) return;
    setBusy(title);
    setError("");
    try {
      const value = await operation();
      setResult({ title, value, at: new Date().toISOString() });
      return value;
    } catch (caught) {
      setError(message(caught));
      throw caught;
    } finally {
      setBusy("");
    }
  }

  const nativeDisabled = Boolean(busy) || restoringNative;

  const handleConnectNative = () =>
    run("Native connected", async () => {
      const connection = await connectNative();
      setNative(connection);
      return connection;
    }).catch(() => undefined);

  const handleNativeAccount = () =>
    run("Native account", async () => getNativeAccount()).catch(() => undefined);

  const handleNativeBalance = () =>
    run("Native balance", async () => {
      const balance = await getNativeBalance();
      setNativeBalance(balance);
      return balance;
    }).catch(() => undefined);

  const handleNativeTransfer = (event: FormEvent) => {
    event.preventDefault();
    if (!window.confirm("Request this real VEX Native mainnet transfer in Wisp Wallet?")) return;
    void run("Native transaction", () => sendNativeTransfer(nativeForm)).catch(() => undefined);
  };

  const handleConnectInjectedEvm = () =>
    run("Wisp EVM connected", async () => {
      const connection = await connectEvm();
      setEvm(connection);
      return connection;
    }).catch(() => undefined);

  const handleConnectWalletConnect = () =>
    run("WalletConnect connected", async () => {
      const provider = await connectWalletConnect();
      const connection = await connectEvm(provider, "WalletConnect v2");
      setEvm(connection);
      return connection;
    }).catch(() => undefined);

  const handleEnsureNetwork = () =>
    run("VEX EVM network ready", async () => {
      const chainId = await ensureVexEvmNetwork();
      setEvm((current) => (current ? { ...current, chainId } : current));
      return chainId;
    }).catch(() => undefined);

  const handleEvmAddress = () =>
    run("EVM address", async () => getEvmAddress()).catch(() => undefined);

  const handleEvmBalance = () =>
    run("EVM balance", async () => {
      const balance = await getEvmBalance();
      setEvmBalance(balance);
      return balance;
    }).catch(() => undefined);

  const handleEvmTransfer = (event: FormEvent) => {
    event.preventDefault();
    if (!window.confirm("Request this real VEX EVM mainnet transfer in Wisp Wallet?")) return;
    void run("EVM transaction", async () => ({
      transactionHash: await sendEvmTransaction(evmForm),
    })).catch(() => undefined);
  };

  const handleNativeDisconnect = () =>
    run("Native disconnected", async () => {
      await disconnectNative();
      setNative(null);
      setNativeBalance("");
      return "Disconnected";
    }).catch(() => undefined);

  const handleEvmDisconnect = () =>
    run("EVM disconnected", async () => {
      if (evm?.method === "WalletConnect v2") await disconnectWalletConnect();
      disconnectEvm();
      setEvm(null);
      setEvmBalance("");
      return "Disconnected";
    }).catch(() => undefined);

  return (
    <main className="page-shell">
      <header className="hero">
        <span className="eyebrow">React + Vite + TypeScript</span>
        <h1>Wisp dApp Example</h1>
        <p>Connect Wisp Wallet, read balances, and send example VEX Native or VEX EVM transactions.</p>
      </header>

      {error && (
        <div className="notice error" role="alert">
          <strong>Request failed</strong>
          <span>{error}</span>
        </div>
      )}
      {busy && <div className="notice pending" role="status">Waiting: {busy}</div>}

      <section className="card full">
        <div className="section-heading">
          <div><span className="step">01</span><h2>Environment</h2></div>
          <span className="status">{environment.runtime}</span>
        </div>
        <dl className="info-grid">
          <Field label="Runtime" value={environment.runtime} />
          <Field label="Secure context" value={environment.isSecureContext ? "Yes" : "No — Wisp Telegram requires HTTPS"} />
          <Field label="Wisp Native" value={environment.hasInjectedNative ? "Available" : "Not detected"} />
          <Field label="Wisp EVM" value={environment.hasInjectedEvm ? "Available" : "Not detected"} />
          <Field label="Native RPC" value={VEX_NATIVE_RPC} />
          <Field label="EVM RPC" value={VEX_EVM_RPC} />
          <Field label="Wisp API" value={WISP_API_URL} />
        </dl>
      </section>

      <div className="columns">
        <section className="card">
          <div className="section-heading">
            <div><span className="step">02</span><h2>VEX Native</h2></div>
            <span className="status">{restoringNative ? "Restoring…" : native?.method || "Disconnected"}</span>
          </div>
          <div className="button-grid">
            <button onClick={handleConnectNative} disabled={nativeDisabled}>Connect Wisp Native</button>
            <button className="secondary" onClick={handleNativeAccount} disabled={nativeDisabled || !native}>Get Account</button>
            <button className="secondary" onClick={handleNativeBalance} disabled={nativeDisabled || !native}>Get VEX Balance</button>
            <button className="ghost" onClick={handleNativeDisconnect} disabled={nativeDisabled || !native}>Disconnect</button>
          </div>
          <p className="hint">A saved Wisp session is checked when the page opens. Connecting is only requested when you press Connect.</p>
          <dl className="compact-info">
            <Field label="Account" value={native?.account.permissionLevel || ""} />
            <Field label="Chain" value={native?.chainId || VEX_NATIVE_CHAIN_ID} />
            <Field label="Balance" value={nativeBalance} />
          </dl>
          <form onSubmit={handleNativeTransfer} className="transaction-form">
            <h3>Native transfer</h3>
            <label>
              Recipient
              <input required value={nativeForm.recipient} onChange={(event) => setNativeForm({ ...nativeForm, recipient: event.target.value })} placeholder="receiver" autoComplete="off" />
            </label>
            <label>
              Amount (VEX)
              <input required inputMode="decimal" value={nativeForm.amount} onChange={(event) => setNativeForm({ ...nativeForm, amount: event.target.value })} />
            </label>
            <label>
              Memo
              <input value={nativeForm.memo} onChange={(event) => setNativeForm({ ...nativeForm, memo: event.target.value })} maxLength={256} />
            </label>
            <button type="submit" disabled={nativeDisabled || !native}>Send Native Transaction</button>
          </form>
        </section>

        <section className="card">
          <div className="section-heading">
            <div><span className="step">03</span><h2>VEX EVM</h2></div>
            <span className="status">{evm?.method || "Disconnected"}</span>
          </div>
          <div className="button-grid">
            <button onClick={handleConnectInjectedEvm} disabled={Boolean(busy)}>Connect Wisp EVM</button>
            <button className="secondary" onClick={handleConnectWalletConnect} disabled={Boolean(busy) || !isWalletConnectConfigured()}>Connect WalletConnect v2</button>
            <button className="secondary" onClick={handleEnsureNetwork} disabled={Boolean(busy) || !evm}>Switch/Add VEX EVM Network</button>
            <button className="secondary" onClick={handleEvmAddress} disabled={Boolean(busy) || !evm}>Get Address</button>
            <button className="secondary" onClick={handleEvmBalance} disabled={Boolean(busy) || !evm}>Get Native VEX Balance</button>
            <button className="ghost" onClick={handleEvmDisconnect} disabled={Boolean(busy) || !evm}>Disconnect</button>
          </div>
          {!isWalletConnectConfigured() && <p className="hint">WalletConnect requires <code>VITE_WALLETCONNECT_PROJECT_ID</code>.</p>}
          <dl className="compact-info">
            <Field label="Address" value={evm?.address || ""} />
            <Field label="Chain" value={evm?.chainId || VEX_EVM_CHAIN_ID_HEX} />
            <Field label="Balance" value={evmBalance} />
          </dl>
          <form onSubmit={handleEvmTransfer} className="transaction-form">
            <h3>EVM transfer</h3>
            <label>
              Recipient
              <input required value={evmForm.recipient} onChange={(event) => setEvmForm({ ...evmForm, recipient: event.target.value })} placeholder="0x..." autoComplete="off" />
            </label>
            <label>
              Amount (VEX)
              <input required inputMode="decimal" value={evmForm.amount} onChange={(event) => setEvmForm({ ...evmForm, amount: event.target.value })} />
            </label>
            <button type="submit" disabled={Boolean(busy) || !evm}>Send EVM Transaction</button>
          </form>
        </section>
      </div>

      <section className="card full">
        <div className="section-heading"><div><span className="step">04</span><h2>Wallet Information</h2></div></div>
        <dl className="info-grid">
          <Field label="Native connection" value={native?.method || "Not connected"} />
          <Field label="Native account" value={native?.account.permissionLevel || ""} />
          <Field label="EVM connection" value={evm?.method || "Not connected"} />
          <Field label="EVM address" value={evm?.address || ""} />
        </dl>
      </section>

      <section className="card full result-card">
        <div className="section-heading">
          <div><span className="step">05</span><h2>Latest Result</h2></div>
          <span className="status">{result ? `${result.title} · ${result.at}` : "No request yet"}</span>
        </div>
        <pre>{result ? JSON.stringify(result.value, null, 2) : "Connect a wallet or send a transaction to see the result."}</pre>
      </section>
    </main>
  );
}
